version: '3.4'

services:
  honeypot:
    build: .
    container_name: adbnectar
    ports:
      - 5555:5555
    volumes:
      - ./logs:/ADBNectar/logs
      - ./captured_samples:/captured_samples
      - ./ADBNectar.cfg:/etc/ADBNectar.cfg
