
cmd_responses = {
"ls": """acct
bt_firmware
bugreports
cache
charger
config
d
data
dev
dsp
etc
firmware
mnt
nonplat_file_contexts
nonplat_property_contexts
nonplat_seapp_contexts
oem
persist
plat_file_contexts
plat_property_contexts
plat_seapp_contexts
plat_service_contexts
proc
res
root
sbin
sdcard
sepolicy
storage
sys
system
tombstones
vendor
ls: ./vndservice_contexts: Permission denied
ls: ./ueventd.rc: Permission denied
ls: ./plat_hwservice_contexts: Permission denied
ls: ./nonplat_service_contexts: Permission denied
ls: ./nonplat_hwservice_contexts: Permission denied
ls: ./init.zygote64_32.rc: Permission denied
ls: ./init.zygote32.rc: Permission denied
ls: ./init.usb.rc: Permission denied
ls: ./init.usb.configfs.rc: Permission denied
ls: ./init.rc: Permission denied
ls: ./init.environ.rc: Permission denied
ls: ./init: Permission denied
ls: ./default.prop: Permission denied
""",

"whoami": """shell
""",

"id": """uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid) context=u:r:shell:s0
""",

"uname -a": """Linux localhost 4.14.186-perf-g1c27e9e #1 SMP PREEMPT Sun Jul 26 01:21:48 UTC 2020 aarch64
""",

"getprop": """[dalvik.vm.appimageformat]: [lz4]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[init.svc.adbd]: [running]
[net.bt.name]: [Android]
[net.dns1]: [8.8.8.8]
[net.dns2]: [8.8.4.4]
[persist.sys.usb.config]: [adb]
[ro.build.id]: [QQ3A.200805.001]
[ro.build.version.release]: [10]
[ro.build.version.sdk]: [29]
[ro.product.board]: [sargo]
[ro.product.brand]: [google]
[ro.product.device]: [sargo]
[ro.product.manufacturer]: [Google]
[ro.product.model]: [Pixel 3a]
[ro.product.name]: [sargo]
[ro.secure]: [1]
[ro.debuggable]: [0]
[sys.usb.state]: [adb]
""",

"cat /system/build.prop": """# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=QQ3A.200805.001
ro.build.display.id=QQ3A.200805.001
ro.build.version.incremental=6841459
ro.build.version.sdk=29
ro.build.version.preview_sdk=0
ro.build.version.release=10
ro.build.version.security_patch=2020-08-05
ro.build.version.base_os=
ro.build.version.min_supported_target_sdk=23
ro.build.date=Sun Jul 26 01:21:48 UTC 2020
ro.build.date.utc=1595726508
ro.build.type=user
ro.build.user=android-build
ro.build.host=abfarm-1234
ro.build.tags=release-keys
ro.build.flavor=sargo-user
ro.build.system_root_image=true
# end build properties

#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.product.model=Pixel 3a
ro.product.brand=google
ro.product.name=sargo
ro.product.device=sargo
ro.product.board=sargo
ro.product.manufacturer=Google
ro.secure=1
ro.debuggable=0
ro.adb.secure=1
""",


# 'Includes popular third-party apps to look more realistic.
"pm list packages": """package:com.android.cts.priv.ctsshim
package:com.google.android.youtube
package:com.google.android.ext.services
package:com.android.providers.telephony
package:com.facebook.katana
package:com.google.android.googlequicksearchbox
package:com.android.providers.calendar
package:com.android.providers.media
package:com.google.android.onetimeinitializer
package:com.instagram.android
package:com.google.android.ext.shared
package:com.android.protips
package:com.android.documentsui
package:com.android.galaxy4
package:com.android.providers.downloads
package:com.mojang.minecraftpe
package:com.android.storagemanager
package:com.google.android.configupdater
package:com.android.defcontainer
package:com.whatsapp
package:com.android.vending
package:com.google.android.gms
package:com.google.android.gsf
package:com.zhiliaoapp.musically
""",

"ps": """USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
root             1     0   10780   4804 SyS_epoll_wait      0 S init
root             2     0       0      0 kthreadd            0 S [kthreadd]
root           512     1   28804   2908 SyS_epoll_wait      0 S ueventd
system         549     1 7136952 145020 SyS_epoll_wait      0 S system_server
shell         8134  8023   11528   3480 0                   0 R ps
u0_a59        2109   987 2348788  98044 SyS_epoll_wait      0 S com.android.systemui
u0_a88        2431   987 2451332 112500 SyS_epoll_wait      0 S com.google.android.googlequicksearchbox:search
u0_a112       2567   987 2890112 153400 SyS_epoll_wait      0 S com.facebook.katana
logd           555     1   57860   6180 SyS_epoll_wait      0 S logd
""",
"ps -A": """USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
root             1     0   10780   4804 SyS_epoll_wait      0 S init
root             2     0       0      0 kthreadd            0 S [kthreadd]
root           512     1   28804   2908 SyS_epoll_wait      0 S ueventd
system         549     1 7136952 145020 SyS_epoll_wait      0 S system_server
shell         8135  8023   11528   3480 0                   0 R ps -A
u0_a59        2109   987 2348788  98044 SyS_epoll_wait      0 S com.android.systemui
u0_a88        2431   987 2451332 112500 SyS_epoll_wait      0 S com.google.android.googlequicksearchbox:search
u0_a112       2567   987 2890112 153400 SyS_epoll_wait      0 S com.facebook.katana
logd           555     1   57860   6180 SyS_epoll_wait      0 S logd
cameraserver   610     1   89020   8804 SyS_epoll_wait      0 S /system/bin/cameraserver
audioserver    611     1  145688  12040 SyS_epoll_wait      0 S /system/bin/audioserver
zygote         987     1 3485724  65432 SyS_epoll_wait      0 S zygote64
""",

"netstat -anp": """Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5037        0.0.0.0:*               LISTEN      -
tcp        0      0 192.168.1.123:44332   54.12.34.56:443         ESTABLISHED 2431/com.google.android.googlequicksearchbox:search
tcp        0      0 192.168.1.123:38910   31.13.78.35:443         ESTABLISHED 2567/com.facebook.katana
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           -
unix  3      [ ]         STREAM     CONNECTED     23456
unix  3      [ ]         STREAM     CONNECTED     12345   549/system_server
""",

"mount": """rootfs on / type rootfs (ro,seclabel,size=1387208k,nr_inodes=346802)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=1481548k,nr_inodes=370387,mode=755)
/dev/block/dm-0 on /system type ext4 (ro,seclabel,relatime,discard)
/dev/block/dm-1 on /vendor type ext4 (ro,seclabel,relatime,discard)
/dev/block/sda23 on /data type f2fs (rw,seclabel,nosuid,nodev,noatime,background_gc=on,discard,user_xattr,inline_xattr,acl,inline_data,inline_dentry,flush_merge,extent_cache,mode=1771,active_logs=6)
/dev/fuse on /storage/emulated type fuse (rw,nosuid,nodev,noexec,noatime,user_id=1023,group_id=1023,default_permissions,allow_other)
""",

"df": """Filesystem       1K-blocks    Used Available Use% Mounted on
tmpfs              1481548     972   1480576   1% /dev
tmpfs              1481548       0   1481548   0% /mnt
/dev/block/dm-0    2894176 2835232     58944  98% /system
/dev/block/dm-1     862208  851000     11208  99% /vendor
/dev/block/sda23  57404192 8415360  48972416  15% /data
/data/media        57404192 8415360  48972416  15% /storage/emulated
""",

# Make it appear like the device has no root access.
"which su": """/system/bin/su: not found
""",

"ls -l /data/local/tmp": """-rwxr-xr-x 1 shell shell 1092344 2025-07-03 10:30 system.log
-rw-rw-rw- 1 shell shell     137 2025-07-03 10:31 output.log
""",

"ls -l /data/data": """ls: /data/data/com.android.providers.media: Permission denied
ls: /data/data/com.google.android.gms: Permission denied
ls: /data/data/com.facebook.katana: Permission denied
ls: /data/data/com.zhiliaoapp.musically: Permission denied
drwxrwx--x  3 shell      shell           4096 2025-07-03 10:30 com.android.shell
"""
}